### ISSUE TITLE
make service docs individually addressable

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylo_services_docs#18]
In order to implement the metadata model fully, it must be possible to provide a URL for the documentation of a service.  This should point to specific information for a service, not to a larger document describing many services (or we risk confusing the user).  

Make the docs for a service individually addressable, either by breaking up into separate docs, or using anchors inside the doc.

**Comment by abusalehmdtayeen** [comment]
This is already done. There are anchors addressing each service individually.

**Comment by arlin** [comment]
Good.
