### ISSUE TITLE
add to docs: how to get access token

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylo_services_docs#20]
Many of the list operations cannot be accessed without an access token.  None of the code examples can be executed for this reason.  

Please add an explanation of how to get an access token.  

This is needed so that @arlin can review the metadata-related tickets.

**Comment by abusalehmdtayeen** [comment]
https://github.com/phylotastic/phylo_services_docs/blob/master/SpeciesListServer/Dev_SpeciesListServicesDescription.md#how-to-get-access-token-to-use-in-species-list-web-services

**Comment by arlin** [comment]
This was enough to get me started, but I was not able to finish.  I have spent about 10 minutes doing this and another 15 trying to figure out how to make it less confusing.  Here is what I suggest: 
1. tell the user what to put in the blanks for the client name and application name in the token-generation process.  My guess is that these don't matter.  If so, tell the user to add something arbitrary.  
1.  the revised URL referring to step 5 should not be placed *after* telling  the user to carry out 9 steps.  The user might carry out all 9 steps, and then see that the URL was wrong.  
1.  explain that the OAuth playground has an accordion labeled "Step 1", "Step 2", "Step 3" whereas the instructions for using it refer to 10 steps.  This is confusing.    
1.  the instructions do not explain what to do after completing step 9.  Please provide specific instructions, with an example URL illustrating how the token would be used.  

I have done about half of these already.  I can't do the last one because I am not sure what to do.

**Comment by arlin** [comment]
<img width="569" alt="screen shot 2017-03-16 at 12 14 59 pm" src="https://cloud.githubusercontent.com/assets/1659198/24006490/57dfb150-0a42-11e7-9d68-94bb11d72fbf.png">

**Comment by abusalehmdtayeen** [comment]
@arlin , please check out my new documentation about getting access tokens. 
https://github.com/phylotastic/phylo_services_docs/blob/master/SpeciesListServer/Dev_SpeciesListServicesDescription.md#how-to-get-access-token-to-use-in-species-list-web-services
