### ISSUE TITLE
Update the webservices document

### ISSUE THREAD

**Issue by abusalehmdtayeen** [phylotastic/phylo_services_docs#3]
Update the web services documentation with species list service api.

**Comment by abusalehmdtayeen** [comment]
Created documentation (https://github.com/phylotastic/phylo_services_docs/blob/master/SpeciesListServer/SpeciesListServicesDescription.md ) for species list services API.

**Comment by hdliv** [comment]
Abu.  I took a look and sent you comments

**Comment by hdliv** [comment]
@abusalehmdtayeen abu and i are working on this issue now

**Comment by hdliv** [comment]
@abusalehmdtayeen Is there more to do on this?

**Comment by abusalehmdtayeen** [comment]
@hdliv : yes,  I am changing the species list services API according to the document you sent me. When I finish that I need to update the species list services API description in that document.

**Comment by abusalehmdtayeen** [comment]
[Species list services API description document](https://github.com/phylotastic/phylo_services_docs/blob/master/SpeciesListServer/SpeciesListServicesDescription.md) is now updated based on the new requirements.

**Comment by hdliv** [comment]
@abusalehmdtayeen I think we are done here...I added 'class' so I think we can close this...

**Comment by arlin** [comment]
yes, this is pretty much done.  However, we need to update the date field description based on the resolution of phylotastic/phylotastic-portal#83

**Comment by hdliv** [comment]
Ok.  I will update it and close this ticket

**Comment by arlin** [comment]
@hdliv you moved this into backlog.  was that an accident?

**Comment by hdliv** [comment]
yes it was.  I had closed and reopened it.  i will move it back

**Comment by arlin** [comment]
So far as I can see, this was not fixed in the docs (https://github.com/phylotastic/phylo_services_docs/blob/master/SpeciesListServer/SpeciesListServicesDescription.md), which still has lines like "Data type: string (format: mm-dd-yyyy)".  According to phylotastic/phylotastic-portal#83, we decided on the ISO standard YYYY-MM-DD.  @abusalehmdtayeen, can you chck on this again?

**Comment by hdliv** [comment]
i must have not saved it before.  fixed

**Comment by arlin** [comment]
OK, thanks.  I see that the dates are fixed.  Closing.
