### ISSUE TITLE
fix possible typo

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylo_services_docs#5]
@abusalehmdtayeen, I reviewed the Ruby code examples in  ServiceDescription/ServiceUsageCodeSamples.md . 

I tested the Ruby examples and they work fine 👍   The only thing I noticed is that "Formica pecefica" is probably supposed to be "Formica pacifica", unless this was a deliberate mis-spelling.  Just let me know and I can fix it.

**Comment by abusalehmdtayeen** [comment]
@arlin : I think I misspelled. Sorry about that. I will fix it.

**Comment by arlin** [comment]
OK, fixed.  Thanks.
