### ISSUE TITLE
metadata for "Resolve Scientific Names with Open Tree TNRS"

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylo_services_docs#6]
For web service 3, add metadata to the information returned by service. The metadata should include

   * search string
   * matched name
   * match type
   * name of resolver
   * number of synonyms
   * list of synonyms

**Comment by arlin** [comment]
Currently the query string is being returned as a comment.  Comments are often tolerated in json but formally there are no comments in valid json, so this is slightly dangerous.  

Please put the query string inside the json.  If you have used a term such as "query" : <query> previously then that is preferable.

**Comment by abusalehmdtayeen** [comment]
Done.
