### ISSUE TITLE
metadata for "Get all Species from a Taxon filtered by country"

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylo_services_docs#7]
For web service 7, add metadata to the information returned by service. The metadata should include

   * input query
   * location queried
   * list of taxa returned
   * number of taxa returned
   * date
   * sources
   * version of both sources

**Comment by abusalehmdtayeen** [comment]
Meta-data added.

**Comment by arlin** [comment]
Good.  See comment for #6.  Remove comments and put query string into json.

**Comment by abusalehmdtayeen** [comment]
The input query parameters are already attached in the json output using properties called "taxon" and "country".
