### ISSUE TITLE
metadata for "Get Species (of a Taxon) that have genome sequence in NCBI"

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylo_services_docs#9]
For web service 9, add metadata to the information returned by service. The metadata should include

   * input query
   * list of taxa returned
   * number of taxa returned
   * date
   * source
   * version of source

**Comment by abusalehmdtayeen** [comment]
Done

**Comment by arlin** [comment]
Good. Same issue as for #6 and others. Please remove comments and put query string in json.

**Comment by abusalehmdtayeen** [comment]
The input query is already attached in the json output using property named "taxon".
